import React, { useState } from "react";
import { Sparkles, Calendar, Download } from "lucide-react";
import Button from "@/components/ui/Button";
import { TripPlanResponse } from "@/types/ai";
import TripSummaryCard from "./TripSummaryCard";
import ItineraryCard from "./ItineraryCard";
import BudgetBreakdown from "./BudgetBreakdown";
import PackingChecklist from "./PackingChecklist";
import LocalFoods from "./LocalFoods";
import TravelTips from "./TravelTips";
import { tripService } from "@/services/trip.service";
import toast from "react-hot-toast";

interface PlannerResultProps {
  result: TripPlanResponse;
  days: number;
  travelers: number;
}

export default function PlannerResult({ result, days, travelers }: PlannerResultProps) {
  const [saveModalOpen, setSaveModalOpen] = useState(false);
  const [startDate, setStartDate] = useState("");
  const [saving, setSaving] = useState(false);

  const handleSaveTrip = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!startDate) return;

    setSaving(true);
    try {
      const start = new Date(startDate);
      const end = new Date(start);
      end.setDate(start.getDate() + days - 1);

      // Clean estimated budget defensively
      let cleanBudget = 0;
      if (typeof result.tripSummary.estimatedBudget === "number") {
        cleanBudget = result.tripSummary.estimatedBudget;
      } else if (result.tripSummary.estimatedBudget) {
        const numericStr = String(result.tripSummary.estimatedBudget).replace(/[^0-9]/g, "");
        cleanBudget = parseInt(numericStr, 10) || 0;
      }

      // Clean budget breakdown numbers defensively
      const cleanBreakdown = {
        accommodation: typeof result.budgetBreakdown?.accommodation === "number"
          ? result.budgetBreakdown.accommodation
          : parseInt(String(result.budgetBreakdown?.accommodation || 0).replace(/[^0-9]/g, ""), 10) || 0,
        food: typeof result.budgetBreakdown?.food === "number"
          ? result.budgetBreakdown.food
          : parseInt(String(result.budgetBreakdown?.food || 0).replace(/[^0-9]/g, ""), 10) || 0,
        transport: typeof result.budgetBreakdown?.transport === "number"
          ? result.budgetBreakdown.transport
          : parseInt(String(result.budgetBreakdown?.transport || 0).replace(/[^0-9]/g, ""), 10) || 0,
        activities: typeof result.budgetBreakdown?.activities === "number"
          ? result.budgetBreakdown.activities
          : parseInt(String(result.budgetBreakdown?.activities || 0).replace(/[^0-9]/g, ""), 10) || 0,
        miscellaneous: typeof result.budgetBreakdown?.miscellaneous === "number"
          ? result.budgetBreakdown.miscellaneous
          : parseInt(String(result.budgetBreakdown?.miscellaneous || 0).replace(/[^0-9]/g, ""), 10) || 0,
      };

      const payload = {
        title: `AI Trip to ${result.tripSummary.destination}`,
        description: `Custom itinerary generated by Mitra AI for ${days} days. Includes ${result.localFoods.length} local food recommendations, budget details, and smart tips.`,
        destination: result.tripSummary.destination,
        startDate: start.toISOString().split("T")[0],
        endDate: end.toISOString().split("T")[0],
        budget: cleanBudget,
        travelers,
        itinerary: result.itinerary,
        budgetBreakdown: cleanBreakdown,
        packingList: result.packingList,
        localFoods: result.localFoods,
        travelTips: result.travelTips,
      };

      const res = await tripService.createTrip(payload);
      if (res.success) {
        toast.success("AI plan saved to your Trip Workspace!");
        setSaveModalOpen(false);
      } else {
        toast.error(res.message || "Failed to save trip.");
      }
    } catch (err) {
      const axiosError = err as { response?: { data?: { message?: string; errors?: { msg: string }[] } } };
      const errMsg = axiosError?.response?.data?.message || axiosError?.response?.data?.errors?.[0]?.msg || "Failed to save trip. Try again.";
      toast.error(errMsg);
    } finally {
      setSaving(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div id="ai-planner-printable" className="space-y-6">
      <TripSummaryCard summary={result.tripSummary} />

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-8 space-y-6">
          <ItineraryCard itinerary={result.itinerary} />
          <LocalFoods localFoods={result.localFoods} />
          <TravelTips travelTips={result.travelTips} />
        </div>
        <div className="lg:col-span-4 space-y-6">
          <BudgetBreakdown budgetBreakdown={result.budgetBreakdown} />
          <PackingChecklist key={result.packingList.join(",")} packingList={result.packingList} />
        </div>
      </div>

      {/* Bottom actions */}
      <div className="flex flex-col sm:flex-row items-center justify-end gap-3 border-t border-border/40 pt-6 print:hidden">
        <Button
          onClick={handlePrint}
          variant="outline"
          className="w-full sm:w-auto gap-2 py-2.5 rounded-xl font-bold"
        >
          <Download className="h-4 w-4" />
          <span>Download PDF</span>
        </Button>
        <Button
          onClick={() => setSaveModalOpen(true)}
          variant="primary"
          className="w-full sm:w-auto gap-2 py-2.5 rounded-xl font-bold"
        >
          <Sparkles className="h-4 w-4 text-white animate-pulse" />
          <span>Save as Trip</span>
        </Button>
      </div>

      {/* Date Picker Modal */}
      {saveModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60 backdrop-blur-sm print:hidden">
          <div className="w-full max-w-md p-6 bg-card border border-border rounded-2xl shadow-xl space-y-4">
            <div className="flex items-center gap-2">
              <Calendar className="h-5 w-5 text-primary" />
              <h3 className="text-sm font-extrabold text-foreground">Select Start Date</h3>
            </div>
            <p className="text-xs text-muted-foreground">
              Choose a start date for your trip to {result.tripSummary.destination}. We will auto-calculate the end date based on your {days}-day itinerary.
            </p>
            <form onSubmit={handleSaveTrip} className="space-y-4">
              <input
                type="date"
                required
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="w-full bg-background border border-border rounded-xl px-4 py-2.5 text-xs font-semibold focus:outline-none"
              />
              <div className="flex justify-end gap-2.5">
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() => setSaveModalOpen(false)}
                >
                  Cancel
                </Button>
                <Button
                  type="submit"
                  variant="primary"
                  size="sm"
                  disabled={saving}
                >
                  {saving ? "Saving..." : "Save Trip"}
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
